name: Cron
on:
  schedule:
    - cron: '* 1 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
